//
// Created by NavKav on 22/07/2025.
//

#ifndef INPUTDEFINITION_H
#define INPUTDEFINITION_H

#define USER_KEY_UNKNOWN 0

// Alphabetical keys
#define USER_KEY_A 4
#define USER_KEY_B 5
#define USER_KEY_C 6
#define USER_KEY_D 7
#define USER_KEY_E 8
#define USER_KEY_F 9
#define USER_KEY_G 10
#define USER_KEY_H 11
#define USER_KEY_I 12
#define USER_KEY_J 13
#define USER_KEY_K 14
#define USER_KEY_L 15
#define USER_KEY_M 16
#define USER_KEY_N 17
#define USER_KEY_O 18
#define USER_KEY_P 19
#define USER_KEY_Q 20
#define USER_KEY_R 21
#define USER_KEY_S 22
#define USER_KEY_T 23
#define USER_KEY_U 24
#define USER_KEY_V 25
#define USER_KEY_W 26
#define USER_KEY_X 27
#define USER_KEY_Y 28
#define USER_KEY_Z 29

// Numeric keys
#define USER_KEY_1 30
#define USER_KEY_2 31
#define USER_KEY_3 32
#define USER_KEY_4 33
#define USER_KEY_5 34
#define USER_KEY_6 35
#define USER_KEY_7 36
#define USER_KEY_8 37
#define USER_KEY_9 38
#define USER_KEY_0 39

// Common special keys
#define USER_KEY_RETURN 40
#define USER_KEY_ESCAPE 41
#define USER_KEY_BACKSPACE 42
#define USER_KEY_TAB 43
#define USER_KEY_SPACE 44
#define USER_KEY_MINUS 45
#define USER_KEY_EQUALS 46
#define USER_KEY_LEFTBRACKET 47
#define USER_KEY_RIGHTBRACKET 48
#define USER_KEY_BACKSLASH 49
#define USER_KEY_NONUSHASH 50
#define USER_KEY_SEMICOLON 51
#define USER_KEY_APOSTROPHE 52
#define USER_KEY_GRAVE 53
#define USER_KEY_COMMA 54
#define USER_KEY_PERIOD 55
#define USER_KEY_SLASH 56
#define USER_KEY_CAPSLOCK 57

// Function keys
#define USER_KEY_F1 58
#define USER_KEY_F2 59
#define USER_KEY_F3 60
#define USER_KEY_F4 61
#define USER_KEY_F5 62
#define USER_KEY_F6 63
#define USER_KEY_F7 64
#define USER_KEY_F8 65
#define USER_KEY_F9 66
#define USER_KEY_F10 67
#define USER_KEY_F11 68
#define USER_KEY_F12 69

// Navigation and editing keys
#define USER_KEY_PRINTSCREEN 70
#define USER_KEY_SCROLLLOCK 71
#define USER_KEY_PAUSE 72
#define USER_KEY_INSERT 73
#define USER_KEY_HOME 74
#define USER_KEY_PAGEUP 75
#define USER_KEY_DELETE 76
#define USER_KEY_END 77
#define USER_KEY_PAGEDOWN 78
#define USER_KEY_RIGHT 79
#define USER_KEY_LEFT 80
#define USER_KEY_DOWN 81
#define USER_KEY_UP 82

// Numeric keypad keys
#define USER_KEY_NUMLOCKCLEAR 83
#define USER_KEY_KP_DIVIDE 84
#define USER_KEY_KP_MULTIPLY 85
#define USER_KEY_KP_MINUS 86
#define USER_KEY_KP_PLUS 87
#define USER_KEY_KP_ENTER 88
#define USER_KEY_KP_1 89
#define USER_KEY_KP_2 90
#define USER_KEY_KP_3 91
#define USER_KEY_KP_4 92
#define USER_KEY_KP_5 93
#define USER_KEY_KP_6 94
#define USER_KEY_KP_7 95
#define USER_KEY_KP_8 96
#define USER_KEY_KP_9 97
#define USER_KEY_KP_0 98
#define USER_KEY_KP_PERIOD 99

// Additional keys
#define USER_KEY_NONUSBACKSLASH 100
#define USER_KEY_APPLICATION 101
#define USER_KEY_POWER 102
#define USER_KEY_KP_EQUALS 103
#define USER_KEY_F13 104
#define USER_KEY_F14 105
#define USER_KEY_F15 106
#define USER_KEY_F16 107
#define USER_KEY_F17 108
#define USER_KEY_F18 109
#define USER_KEY_F19 110
#define USER_KEY_F20 111
#define USER_KEY_F21 112
#define USER_KEY_F22 113
#define USER_KEY_F23 114
#define USER_KEY_F24 115
#define USER_KEY_EXECUTE 116
#define USER_KEY_HELP 117
#define USER_KEY_MENU 118
#define USER_KEY_SELECT 119
#define USER_KEY_STOP 120
#define USER_KEY_AGAIN 121
#define USER_KEY_UNDO 122
#define USER_KEY_CUT 123
#define USER_KEY_COPY 124
#define USER_KEY_PASTE 125
#define USER_KEY_FIND 126
#define USER_KEY_MUTE 127
#define USER_KEY_VOLUMEUP 128
#define USER_KEY_VOLUMEDOWN 129
#define USER_KEY_KP_COMMA 133
#define USER_KEY_KP_EQUALSAS400 134

// International and Language keys
#define USER_KEY_INTERNATIONAL1 135
#define USER_KEY_INTERNATIONAL2 136
#define USER_KEY_INTERNATIONAL3 137
#define USER_KEY_INTERNATIONAL4 138
#define USER_KEY_INTERNATIONAL5 139
#define USER_KEY_INTERNATIONAL6 140
#define USER_KEY_INTERNATIONAL7 141
#define USER_KEY_INTERNATIONAL8 142
#define USER_KEY_INTERNATIONAL9 143
#define USER_KEY_LANG1 144
#define USER_KEY_LANG2 145
#define USER_KEY_LANG3 146
#define USER_KEY_LANG4 147
#define USER_KEY_LANG5 148
#define USER_KEY_LANG6 149
#define USER_KEY_LANG7 150
#define USER_KEY_LANG8 151
#define USER_KEY_LANG9 152

// Other specialized keys
#define USER_KEY_ALTERASE 153
#define USER_KEY_SYSREQ 154
#define USER_KEY_CANCEL 155
#define USER_KEY_CLEAR 156
#define USER_KEY_PRIOR 157
#define USER_KEY_RETURN2 158
#define USER_KEY_SEPARATOR 159
#define USER_KEY_OUT 160
#define USER_KEY_OPER 161
#define USER_KEY_CLEARAGAIN 162
#define USER_KEY_CRSEL 163
#define USER_KEY_EXSEL 164

// Additional numeric keypad keys
#define USER_KEY_KP_00 176
#define USER_KEY_KP_000 177
#define USER_KEY_THOUSANDSSEPARATOR 178
#define USER_KEY_DECIMALSEPARATOR 179
#define USER_KEY_CURRENCYUNIT 180
#define USER_KEY_CURRENCYSUBUNIT 181
#define USER_KEY_KP_LEFTPAREN 182
#define USER_KEY_KP_RIGHTPAREN 183
#define USER_KEY_KP_LEFTBRACE 184
#define USER_KEY_KP_RIGHTBRACE 185
#define USER_KEY_KP_TAB 186
#define USER_KEY_KP_BACKSPACE 187
#define USER_KEY_KP_A 188
#define USER_KEY_KP_B 189
#define USER_KEY_KP_C 190
#define USER_KEY_KP_D 191
#define USER_KEY_KP_E 192
#define USER_KEY_KP_F 193
#define USER_KEY_KP_XOR 194
#define USER_KEY_KP_POWER 195
#define USER_KEY_KP_PERCENT 196
#define USER_KEY_KP_LESS 197
#define USER_KEY_KP_GREATER 198
#define USER_KEY_KP_AMPERSAND 199
#define USER_KEY_KP_DBLAMPERSAND 200
#define USER_KEY_KP_VERTICALBAR 201
#define USER_KEY_KP_DBLVERTICALBAR 202
#define USER_KEY_KP_COLON 203
#define USER_KEY_KP_HASH 204
#define USER_KEY_KP_SPACE 205
#define USER_KEY_KP_AT 206
#define USER_KEY_KP_EXCLAM 207
#define USER_KEY_KP_MEMSTORE 208
#define USER_KEY_KP_MEMRECALL 209
#define USER_KEY_KP_MEMCLEAR 210
#define USER_KEY_KP_MEMADD 211
#define USER_KEY_KP_MEMSUBTRACT 212
#define USER_KEY_KP_MEMMULTIPLY 213
#define USER_KEY_KP_MEMDIVIDE 214
#define USER_KEY_KP_PLUSMINUS 215
#define USER_KEY_KP_CLEAR 216
#define USER_KEY_KP_CLEARENTRY 217
#define USER_KEY_KP_BINARY 218
#define USER_KEY_KP_OCTAL 219
#define USER_KEY_KP_DECIMAL 220
#define USER_KEY_KP_HEXADECIMAL 221

// Modifier keys
#define USER_KEY_LCTRL 224
#define USER_KEY_LSHIFT 225
#define USER_KEY_LALT 226
#define USER_KEY_LGUI 227
#define USER_KEY_RCTRL 228
#define USER_KEY_RSHIFT 229
#define USER_KEY_RALT 230
#define USER_KEY_RGUI 231

#define USER_KEY_MODE 257

// Audio and media keys
#define USER_KEY_AUDIONEXT 258
#define USER_KEY_AUDIOPREV 259
#define USER_KEY_AUDIOSTOP 260
#define USER_KEY_AUDIOPLAY 261
#define USER_KEY_AUDIOMUTE 262
#define USER_KEY_MEDIASELECT 263
#define USER_KEY_WWW 264
#define USER_KEY_MAIL 265
#define USER_KEY_CALCULATOR 266
#define USER_KEY_COMPUTER 267
#define USER_KEY_AC_SEARCH 268
#define USER_KEY_AC_HOME 269
#define USER_KEY_AC_BACK 270
#define USER_KEY_AC_FORWARD 271
#define USER_KEY_AC_STOP 272
#define USER_KEY_AC_REFRESH 273
#define USER_KEY_AC_BOOKMARKS 274

// Brightness and display keys
#define USER_KEY_BRIGHTNESSDOWN 275
#define USER_KEY_BRIGHTNESSUP 276
#define USER_KEY_DISPLAYSWITCH 277
#define USER_KEY_KBDILLUMTOGGLE 278
#define USER_KEY_KBDILLUMDOWN 279
#define USER_KEY_KBDILLUMUP 280
#define USER_KEY_EJECT 281
#define USER_KEY_SLEEP 282

#define USER_KEY_APP1 283
#define USER_KEY_APP2 284

#define USER_KEY_AUDIOREWIND 285
#define USER_KEY_AUDIOFASTFORWARD 286

// Mobile keys
#define USER_KEY_SOFTLEFT 287
#define USER_KEY_SOFTRIGHT 288
#define USER_KEY_CALL 289
#define USER_KEY_ENDCALL 290

#define USER_NUM_SCANCODES 512

#endif //INPUTDEFINITION_H
